# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release-tags

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
        # cache-dependency-path: go.sum
        
    - name: Install dependencies
      run: go mod tidy
      
    - name: Build
      run: bash scripts/build.sh -a

    # - name: version
    #   run: echo "::set-output name=version::$(go run cmd/kd.go --version | awk '{print $3}')"
    #   id: version

    - name: Generate Changelog
      run: echo "由changelog生成" > ${{ github.workspace }}-CHANGELOG.txt

    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        name: test-${{ steps.version.outputs.version }}
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        fail_on_unmatched_files: true
        tag_name: v0.0.1
        prerelease: true
        files: build/*

    - name: info
      run: echo ${{ steps.Release.outputs.url }} ${{ steps.Release.outputs.upload_url }} ${{ steps.Release.outputs.id }}
      

